services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command : bash -c 'cd app && yarn dev'
    volumes:
      - ./app:/app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000"
